version: "3.9"

services:
  client:
    build: ./client
    container_name: client_test
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    container_name: backend_test
    ports:
      - "8080:8080"
  agent:
    build: ./agent
    container_name: agent_test
  analyzer:
    build: ./analyzer
    container_name: analyzer_test
