{{- if .Values.backendroute.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.backendroute.name }}
  namespace: {{ .Values.namespace }}
spec:
  path: {{ .Values.backendroute.path }}
  to:
    kind: Service
    name: {{ .Values.backendroute.serviceName }}
  port:
    targetPort: {{ .Values.backend.port }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
