apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: edge-app-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.label }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1011790000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ .Values.backend.containerName }}
          image: {{ .Values.backend.image }}:{{ .Values.backend.tag }}
          ports:
            - containerPort: {{ .Values.backend.port }}
              protocol: TCP
          env:
            - name: PORT
              value: "{{ .Values.backend.port }}"
          envFrom:
            - secretRef:
                name: {{ .Values.backend.secretName }}
          resources:
            limits:
              cpu: {{ .Values.backend.resources.limits.cpu | quote }}
              memory: {{ .Values.backend.resources.limits.memory | quote }}
            requests:
              cpu: {{ .Values.backend.resources.requests.cpu | quote }}
              memory: {{ .Values.backend.resources.requests.memory | quote }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 6
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false 
            capabilities:
              drop: ["ALL"]
