apiVersion: v1
kind: Secret
metadata:
  name: edge-frontend-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  INTERNAL_API_URL: {{.Values.frontend.secret.INTERNAL_API_URL}}
  NEXT_PUBLIC_BACKEND_URL: {{.Values.frontend.secret.NEXT_PUBLIC_BACKEND_URL}}
  PORT: "{{.Values.frontend.secret.PORT}}"


---
apiVersion: v1
kind: Secret
metadata:
  name: edge-backend-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  PORT: "{{ .Values.backend.port }}"

  DBURL: {{ .Values.backend.secret.DBURL | quote }}
  DB_HOST: {{ .Values.backend.secret.DB_HOST | quote }}
  DB_PORT: "{{ .Values.backend.secret.DB_PORT }}"
  DB_NAME: {{ .Values.backend.secret.DB_NAME | quote }}
  DB_USER: {{ .Values.backend.secret.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.backend.secret.DB_PASSWORD | quote }}

  JWT_SECRET: {{ .Values.backend.secret.JWT_SECRET | quote }}

  FRONT_END_URL: {{ .Values.backend.secret.FRONT_END_URL | quote }}

  GOOGLE_CLIENT_ID: {{ .Values.backend.secret.GOOGLE_CLIENT_ID | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.backend.secret.GOOGLE_CLIENT_SECRET | quote }}
  GOOGLE_REDIRECT_URL: {{ .Values.backend.secret.GOOGLE_REDIRECT_URL | quote }}

  GITHUB_CLIENT_ID: {{ .Values.backend.secret.GITHUB_CLIENT_ID | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.backend.secret.GITHUB_CLIENT_SECRET | quote }}
  GITHUB_REDIRECT_URL: {{ .Values.backend.secret.GITHUB_REDIRECT_URL | quote }}

  BREVO_API_KEY: {{ .Values.backend.secret.BREVO_API_KEY | quote }}
  BREVO_HOST: {{ .Values.backend.secret.BREVO_HOST | quote }}
  BREVO_SMTP_KEY: {{ .Values.backend.secret.BREVO_SMTP_KEY | quote }}
  BREVO_USER: {{ .Values.backend.secret.BREVO_USER | quote }}

  GMAIL_PASSWORD: {{ .Values.backend.secret.GMAIL_PASSWORD | quote }}
