// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 2FA.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const create2FA = `-- name: Create2FA :exec
INSERT INTO user_2fa_tokens (user_id, fa_secret, isEnabled) 
VALUES ($1, $2, $3)
`

type Create2FAParams struct {
	UserID    int64
	FaSecret  string
	Isenabled pgtype.Bool
}

func (q *Queries) Create2FA(ctx context.Context, arg Create2FAParams) error {
	_, err := q.db.Exec(ctx, create2FA, arg.UserID, arg.FaSecret, arg.Isenabled)
	return err
}

const get2FAByUser = `-- name: Get2FAByUser :one
SELECT id, user_id, fa_secret, isenabled FROM user_2fa_tokens WHERE user_id = $1
`

func (q *Queries) Get2FAByUser(ctx context.Context, userID int64) (User2faToken, error) {
	row := q.db.QueryRow(ctx, get2FAByUser, userID)
	var i User2faToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FaSecret,
		&i.Isenabled,
	)
	return i, err
}

const is2FAEnabled = `-- name: Is2FAEnabled :one
SELECT isEnabled FROM user_2fa_tokens WHERE user_id = $1
`

func (q *Queries) Is2FAEnabled(ctx context.Context, userID int64) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, is2FAEnabled, userID)
	var isenabled pgtype.Bool
	err := row.Scan(&isenabled)
	return isenabled, err
}

const updateIs2FAEnabled = `-- name: UpdateIs2FAEnabled :exec
UPDATE user_2fa_tokens SET isEnabled = $1 WHERE user_id = $2
`

type UpdateIs2FAEnabledParams struct {
	Isenabled pgtype.Bool
	UserID    int64
}

func (q *Queries) UpdateIs2FAEnabled(ctx context.Context, arg UpdateIs2FAEnabledParams) error {
	_, err := q.db.Exec(ctx, updateIs2FAEnabled, arg.Isenabled, arg.UserID)
	return err
}
