// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_queue.sql

package db

import (
	"context"
)

const createAgentQueue = `-- name: CreateAgentQueue :exec
INSERT INTO agent_queue(agent_id, event) VALUES ($1, $2)
`

type CreateAgentQueueParams struct {
	AgentID int64
	Event   []byte
}

func (q *Queries) CreateAgentQueue(ctx context.Context, arg CreateAgentQueueParams) error {
	_, err := q.db.Exec(ctx, createAgentQueue, arg.AgentID, arg.Event)
	return err
}

const getAgentQueueByID = `-- name: GetAgentQueueByID :one
SELECT id, agent_id, event, created_at from agent_queue WHERE id = $1
`

func (q *Queries) GetAgentQueueByID(ctx context.Context, id int64) (AgentQueue, error) {
	row := q.db.QueryRow(ctx, getAgentQueueByID, id)
	var i AgentQueue
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Event,
		&i.CreatedAt,
	)
	return i, err
}

const getAllAgentQueue = `-- name: GetAllAgentQueue :one
SELECT id, agent_id, event, created_at FROM agent_queue LIMIT  50
`

func (q *Queries) GetAllAgentQueue(ctx context.Context) (AgentQueue, error) {
	row := q.db.QueryRow(ctx, getAllAgentQueue)
	var i AgentQueue
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.Event,
		&i.CreatedAt,
	)
	return i, err
}

const updateAgentById = `-- name: UpdateAgentById :exec
UPDATE agent_queue
SET
    agent_id = COALESCE($1, agent_id),
    event = COALESCE($2, event)
WHERE id = $3
`

type UpdateAgentByIdParams struct {
	AgentID int64
	Event   []byte
	ID      int64
}

func (q *Queries) UpdateAgentById(ctx context.Context, arg UpdateAgentByIdParams) error {
	_, err := q.db.Exec(ctx, updateAgentById, arg.AgentID, arg.Event, arg.ID)
	return err
}
