// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_telemetry.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestTelemetry = `-- name: GetLatestTelemetry :one
SELECT agent_id, machine_id, agent_token, last_updated, system_data, security_data, processes_data, integrity_data, network_data, expires_at FROM agent_telemetry_latest WHERE agent_id = $1
`

func (q *Queries) GetLatestTelemetry(ctx context.Context, agentID string) (AgentTelemetryLatest, error) {
	row := q.db.QueryRow(ctx, getLatestTelemetry, agentID)
	var i AgentTelemetryLatest
	err := row.Scan(
		&i.AgentID,
		&i.MachineID,
		&i.AgentToken,
		&i.LastUpdated,
		&i.SystemData,
		&i.SecurityData,
		&i.ProcessesData,
		&i.IntegrityData,
		&i.NetworkData,
		&i.ExpiresAt,
	)
	return i, err
}

const listActiveAgents = `-- name: ListActiveAgents :many
SELECT agent_id, last_updated
FROM agent_telemetry_latest
WHERE last_updated > NOW() - INTERVAL '1 hour'
ORDER BY last_updated DESC
`

type ListActiveAgentsRow struct {
	AgentID     string
	LastUpdated pgtype.Timestamptz
}

func (q *Queries) ListActiveAgents(ctx context.Context) ([]ListActiveAgentsRow, error) {
	rows, err := q.db.Query(ctx, listActiveAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveAgentsRow
	for rows.Next() {
		var i ListActiveAgentsRow
		if err := rows.Scan(&i.AgentID, &i.LastUpdated); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgentTelemetry = `-- name: UpsertAgentTelemetry :exec
INSERT INTO agent_telemetry_latest (
    agent_id, machine_id, agent_token,
    system_data, security_data, processes_data, integrity_data, network_data,
    last_updated 
)
VALUES (
    $1, $2, $3,
    $4::jsonb, $5::jsonb, $6::jsonb, $7::jsonb, $8::jsonb,
    NOW()
)
ON CONFLICT (agent_id) DO UPDATE SET
    agent_id       = EXCLUDED.agent_id,
    machine_id     = EXCLUDED.machine_id,
    agent_token    = EXCLUDED.agent_token,
    system_data    = EXCLUDED.system_data,
    security_data  = EXCLUDED.security_data,
    processes_data = EXCLUDED.processes_data,
    integrity_data = EXCLUDED.integrity_data,
    network_data   = EXCLUDED.network_data,
    last_updated   = NOW()
`

type UpsertAgentTelemetryParams struct {
	AgentID    string
	MachineID  string
	AgentToken pgtype.Text
	Column4    []byte
	Column5    []byte
	Column6    []byte
	Column7    []byte
	Column8    []byte
}

func (q *Queries) UpsertAgentTelemetry(ctx context.Context, arg UpsertAgentTelemetryParams) error {
	_, err := q.db.Exec(ctx, upsertAgentTelemetry,
		arg.AgentID,
		arg.MachineID,
		arg.AgentToken,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
	)
	return err
}
