// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgent = `-- name: CreateAgent :exec
INSERT INTO agents(user_id, agent_id, agent_token, machine_id, agent_version, os, status, last_seen) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAgentParams struct {
	UserID       int64
	AgentID      int64
	AgentToken   string
	MachineID    string
	AgentVersion pgtype.Text
	Os           pgtype.Text
	Status       pgtype.Text
	LastSeen     pgtype.Timestamptz
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) error {
	_, err := q.db.Exec(ctx, createAgent,
		arg.UserID,
		arg.AgentID,
		arg.AgentToken,
		arg.MachineID,
		arg.AgentVersion,
		arg.Os,
		arg.Status,
		arg.LastSeen,
	)
	return err
}

const getAgentByAgentId = `-- name: GetAgentByAgentId :one
SELECT id, user_id, agent_id, agent_token, machine_id, agent_version, os, status, last_seen, created_at from agents WHERE agent_id = $1
`

func (q *Queries) GetAgentByAgentId(ctx context.Context, agentID int64) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentByAgentId, agentID)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.AgentToken,
		&i.MachineID,
		&i.AgentVersion,
		&i.Os,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const getAgentById = `-- name: GetAgentById :one
SELECT id, user_id, agent_id, agent_token, machine_id, agent_version, os, status, last_seen, created_at from agents WHERE id = $1
`

func (q *Queries) GetAgentById(ctx context.Context, id int64) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentById, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.AgentToken,
		&i.MachineID,
		&i.AgentVersion,
		&i.Os,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const getAllAgent = `-- name: GetAllAgent :one
SELECT id, user_id, agent_id, agent_token, machine_id, agent_version, os, status, last_seen, created_at FROM agents LIMIT  50
`

func (q *Queries) GetAllAgent(ctx context.Context) (Agent, error) {
	row := q.db.QueryRow(ctx, getAllAgent)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AgentID,
		&i.AgentToken,
		&i.MachineID,
		&i.AgentVersion,
		&i.Os,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const getUserDeviceCount = `-- name: GetUserDeviceCount :one
SELECT COUNT(*) from agents WHERE user_id = $1
`

func (q *Queries) GetUserDeviceCount(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getUserDeviceCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateSingleAgent = `-- name: UpdateSingleAgent :exec
UPDATE agents
SET
    user_id       = COALESCE($1, user_id),
    agent_id = COALESCE($2, agent_id),
    agent_token = COALESCE($3, agent_token),
    machine_id    = COALESCE($4, machine_id),
    agent_version = COALESCE($5, agent_version),
    os            = COALESCE($6, os),
    status        = COALESCE($7, status),
    last_seen     = COALESCE($8, last_seen)
WHERE id = $9
`

type UpdateSingleAgentParams struct {
	UserID       int64
	AgentID      int64
	AgentToken   string
	MachineID    string
	AgentVersion pgtype.Text
	Os           pgtype.Text
	Status       pgtype.Text
	LastSeen     pgtype.Timestamptz
	ID           int64
}

func (q *Queries) UpdateSingleAgent(ctx context.Context, arg UpdateSingleAgentParams) error {
	_, err := q.db.Exec(ctx, updateSingleAgent,
		arg.UserID,
		arg.AgentID,
		arg.AgentToken,
		arg.MachineID,
		arg.AgentVersion,
		arg.Os,
		arg.Status,
		arg.LastSeen,
		arg.ID,
	)
	return err
}
