// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgent = `-- name: CreateAgent :exec
INSERT INTO agents(user_id, machine_id, agent_version, os, status, last_seen) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAgentParams struct {
	UserID       int64
	MachineID    string
	AgentVersion pgtype.Text
	Os           pgtype.Text
	Status       pgtype.Text
	LastSeen     pgtype.Timestamptz
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) error {
	_, err := q.db.Exec(ctx, createAgent,
		arg.UserID,
		arg.MachineID,
		arg.AgentVersion,
		arg.Os,
		arg.Status,
		arg.LastSeen,
	)
	return err
}

const getAgentById = `-- name: GetAgentById :one
SELECT id, user_id, machine_id, agent_version, os, status, last_seen, created_at from agents WHERE id = $1
`

func (q *Queries) GetAgentById(ctx context.Context, id int64) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentById, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MachineID,
		&i.AgentVersion,
		&i.Os,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const getAllAgent = `-- name: GetAllAgent :one
SELECT id, user_id, machine_id, agent_version, os, status, last_seen, created_at FROM agents LIMIT  50
`

func (q *Queries) GetAllAgent(ctx context.Context) (Agent, error) {
	row := q.db.QueryRow(ctx, getAllAgent)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MachineID,
		&i.AgentVersion,
		&i.Os,
		&i.Status,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const updateSingleAgent = `-- name: UpdateSingleAgent :exec
UPDATE agents
SET
    user_id       = COALESCE($1, user_id),
    machine_id    = COALESCE($2, machine_id),
    agent_version = COALESCE($3, agent_version),
    os            = COALESCE($4, os),
    status        = COALESCE($5, status),
    last_seen     = COALESCE($6, last_seen)
WHERE id = $7
`

type UpdateSingleAgentParams struct {
	UserID       int64
	MachineID    string
	AgentVersion pgtype.Text
	Os           pgtype.Text
	Status       pgtype.Text
	LastSeen     pgtype.Timestamptz
	ID           int64
}

func (q *Queries) UpdateSingleAgent(ctx context.Context, arg UpdateSingleAgentParams) error {
	_, err := q.db.Exec(ctx, updateSingleAgent,
		arg.UserID,
		arg.MachineID,
		arg.AgentVersion,
		arg.Os,
		arg.Status,
		arg.LastSeen,
		arg.ID,
	)
	return err
}
