// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlert = `-- name: CreateAlert :exec
INSERT INTO alerts(agent_id, alert_type, severity,  status, message, raw_payload) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAlertParams struct {
	AgentID    int64
	AlertType  string
	Severity   string
	Status     string
	Message    pgtype.Text
	RawPayload []byte
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) error {
	_, err := q.db.Exec(ctx, createAlert,
		arg.AgentID,
		arg.AlertType,
		arg.Severity,
		arg.Status,
		arg.Message,
		arg.RawPayload,
	)
	return err
}

const getAlertById = `-- name: GetAlertById :one
SELECT id, agent_id, alert_type, severity, message, raw_payload, status, created_at from alerts WHERE id = $1
`

func (q *Queries) GetAlertById(ctx context.Context, id int64) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlertById, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.AlertType,
		&i.Severity,
		&i.Message,
		&i.RawPayload,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAllAlert = `-- name: GetAllAlert :one
SELECT id, agent_id, alert_type, severity, message, raw_payload, status, created_at FROM alerts LIMIT 50
`

func (q *Queries) GetAllAlert(ctx context.Context) (Alert, error) {
	row := q.db.QueryRow(ctx, getAllAlert)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.AlertType,
		&i.Severity,
		&i.Message,
		&i.RawPayload,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateSingleAlert = `-- name: UpdateSingleAlert :exec
UPDATE alerts
SET
    agent_id = COALESCE($1, agent_id),
    alert_type = COALESCE($2, alert_type),
    severity = COALESCE($3, severity),
    message = COALESCE($4, message),
    status        = COALESCE($5, status),
    raw_payload     = COALESCE($6, raw_payload)
WHERE id = $7
`

type UpdateSingleAlertParams struct {
	AgentID    int64
	AlertType  string
	Severity   string
	Message    pgtype.Text
	Status     string
	RawPayload []byte
	ID         int64
}

func (q *Queries) UpdateSingleAlert(ctx context.Context, arg UpdateSingleAlertParams) error {
	_, err := q.db.Exec(ctx, updateSingleAlert,
		arg.AgentID,
		arg.AlertType,
		arg.Severity,
		arg.Message,
		arg.Status,
		arg.RawPayload,
		arg.ID,
	)
	return err
}
