// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlert = `-- name: CreateAlert :exec
INSERT INTO alerts (
  agent_id,
  agent_token,
  alert_type,
  severity,
  message,
  raw_payload,
  status,
  risk_level,
  summary,
  performance,
  network,
  security,
  created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
`

type CreateAlertParams struct {
	AgentID     int64
	AgentToken  string
	AlertType   string
	Severity    string
	Message     pgtype.Text
	RawPayload  []byte
	Status      string
	RiskLevel   pgtype.Text
	Summary     pgtype.Text
	Performance []byte
	Network     []byte
	Security    []byte
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) error {
	_, err := q.db.Exec(ctx, createAlert,
		arg.AgentID,
		arg.AgentToken,
		arg.AlertType,
		arg.Severity,
		arg.Message,
		arg.RawPayload,
		arg.Status,
		arg.RiskLevel,
		arg.Summary,
		arg.Performance,
		arg.Network,
		arg.Security,
		arg.CreatedAt,
	)
	return err
}

const getAlertById = `-- name: GetAlertById :one
SELECT id, agent_id, agent_token, alert_type, severity, message, raw_payload, status, risk_level, summary, performance, network, security, created_at from alerts WHERE id = $1
`

func (q *Queries) GetAlertById(ctx context.Context, id int64) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlertById, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.AgentToken,
		&i.AlertType,
		&i.Severity,
		&i.Message,
		&i.RawPayload,
		&i.Status,
		&i.RiskLevel,
		&i.Summary,
		&i.Performance,
		&i.Network,
		&i.Security,
		&i.CreatedAt,
	)
	return i, err
}

const getAllAlert = `-- name: GetAllAlert :one
SELECT id, agent_id, agent_token, alert_type, severity, message, raw_payload, status, risk_level, summary, performance, network, security, created_at FROM alerts WHERE agent_id = $1
`

func (q *Queries) GetAllAlert(ctx context.Context, agentID int64) (Alert, error) {
	row := q.db.QueryRow(ctx, getAllAlert, agentID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.AgentToken,
		&i.AlertType,
		&i.Severity,
		&i.Message,
		&i.RawPayload,
		&i.Status,
		&i.RiskLevel,
		&i.Summary,
		&i.Performance,
		&i.Network,
		&i.Security,
		&i.CreatedAt,
	)
	return i, err
}

const updateSingleAlert = `-- name: UpdateSingleAlert :exec
UPDATE alerts
SET
    agent_id     = COALESCE($1, agent_id),
    agent_token  = COALESCE($2, agent_token),
    alert_type   = COALESCE($3, alert_type),
    severity     = COALESCE($4, severity),
    message      = COALESCE($5, message),
    status       = COALESCE($6, status),
    raw_payload  = COALESCE($7, raw_payload),
    created_at   = COALESCE($8, created_at),
    risk_level   = COALESCE($9, risk_level),
    summary      = COALESCE($10, summary),
    performance  = COALESCE($11, performance),
    network      = COALESCE($12, network),
    security     = COALESCE($13, security)
WHERE id = $14
`

type UpdateSingleAlertParams struct {
	AgentID     int64
	AgentToken  string
	AlertType   string
	Severity    string
	Message     pgtype.Text
	Status      string
	RawPayload  []byte
	CreatedAt   pgtype.Timestamptz
	RiskLevel   pgtype.Text
	Summary     pgtype.Text
	Performance []byte
	Network     []byte
	Security    []byte
	ID          int64
}

func (q *Queries) UpdateSingleAlert(ctx context.Context, arg UpdateSingleAlertParams) error {
	_, err := q.db.Exec(ctx, updateSingleAlert,
		arg.AgentID,
		arg.AgentToken,
		arg.AlertType,
		arg.Severity,
		arg.Message,
		arg.Status,
		arg.RawPayload,
		arg.CreatedAt,
		arg.RiskLevel,
		arg.Summary,
		arg.Performance,
		arg.Network,
		arg.Security,
		arg.ID,
	)
	return err
}
