// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: commands.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCommand = `-- name: CreateCommand :exec
INSERT INTO commands(agent_id, user_id, command_type, payload, status, updated_at) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateCommandParams struct {
	AgentID     int64
	UserID      int64
	CommandType string
	Payload     []byte
	Status      string
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateCommand(ctx context.Context, arg CreateCommandParams) error {
	_, err := q.db.Exec(ctx, createCommand,
		arg.AgentID,
		arg.UserID,
		arg.CommandType,
		arg.Payload,
		arg.Status,
		arg.UpdatedAt,
	)
	return err
}

const getAllCommands = `-- name: GetAllCommands :one
SELECT id, agent_id, user_id, command_type, payload, status, created_at, updated_at FROM commands LIMIT 50
`

func (q *Queries) GetAllCommands(ctx context.Context) (Command, error) {
	row := q.db.QueryRow(ctx, getAllCommands)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.UserID,
		&i.CommandType,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommandById = `-- name: GetCommandById :one
SELECT id, agent_id, user_id, command_type, payload, status, created_at, updated_at from commands WHERE id = $1
`

func (q *Queries) GetCommandById(ctx context.Context, id int64) (Command, error) {
	row := q.db.QueryRow(ctx, getCommandById, id)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.UserID,
		&i.CommandType,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCommandById = `-- name: UpdateCommandById :exec
UPDATE commands
SET
    agent_id = COALESCE($1, agent_id),
    user_id       = COALESCE($2, user_id),
    command_type = COALESCE($3, command_type),
    payload = COALESCE($4,  payload),
    status = COALESCE($5, status),
    updated_at = COALESCE($6, updated_at)
WHERE id = $7
`

type UpdateCommandByIdParams struct {
	AgentID     int64
	UserID      int64
	CommandType string
	Payload     []byte
	Status      string
	UpdatedAt   pgtype.Timestamptz
	ID          int64
}

func (q *Queries) UpdateCommandById(ctx context.Context, arg UpdateCommandByIdParams) error {
	_, err := q.db.Exec(ctx, updateCommandById,
		arg.AgentID,
		arg.UserID,
		arg.CommandType,
		arg.Payload,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
