// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID           int64
	DeviceName   string
	UserID       int64
	AgentID      string
	AgentToken   string
	MachineID    string
	AgentVersion pgtype.Text
	Os           pgtype.Text
	Status       pgtype.Text
	LastSeen     pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type AgentQueue struct {
	ID        int64
	AgentID   int64
	Event     []byte
	CreatedAt pgtype.Timestamptz
}

type Alert struct {
	ID          int64
	AgentID     string
	AgentToken  string
	AlertType   string
	Severity    string
	Message     pgtype.Text
	RawPayload  []byte
	Status      string
	RiskLevel   pgtype.Text
	Summary     pgtype.Text
	Performance []byte
	Network     []byte
	Security    []byte
	CreatedAt   pgtype.Timestamptz
}

type Command struct {
	ID          int64
	UserID      int64
	AgentID     string
	CommandType string
	Payload     []byte
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Notification struct {
	ID        int64
	UserID    int64
	Title     string
	Message   string
	IsRead    bool
	CreatedAt pgtype.Timestamptz
}

type PairingToken struct {
	ID        int64
	Token     string
	UserID    int32
	UserEmail string
	ExpiresAt pgtype.Timestamptz
}

type User struct {
	ID        int32
	Name      string
	Photo     pgtype.Text
	Phone     pgtype.Text
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
}

type UserSession struct {
	ID        int64
	UserID    int64
	Token     string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}
