// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int32
	Name      string
	Photo     pgtype.Text
	Phone     pgtype.Text
	Email     string
	Password  string
	CreatedAt string
}
