// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package db

import (
	"context"
)

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications(user_id, title, message, is_read) VALUES ($1, $2, $3, $4)
`

type CreateNotificationParams struct {
	UserID  int64
	Title   string
	Message string
	IsRead  bool
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.Exec(ctx, createNotification,
		arg.UserID,
		arg.Title,
		arg.Message,
		arg.IsRead,
	)
	return err
}

const getAllNotifications = `-- name: GetAllNotifications :many
SELECT id, user_id, title, message, is_read, created_at FROM notifications WHERE user_id = $1 AND is_read = false ORDER BY id DESC LIMIT 50
`

func (q *Queries) GetAllNotifications(ctx context.Context, userID int64) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getAllNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Message,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationById = `-- name: GetNotificationById :one
SELECT id, user_id, title, message, is_read, created_at from notifications WHERE id = $1 AND user_id = $2
`

type GetNotificationByIdParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetNotificationById(ctx context.Context, arg GetNotificationByIdParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationById, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Message,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const updateAllNotificationByUserId = `-- name: UpdateAllNotificationByUserId :exec
UPDATE notifications SET is_read = true WHERE user_id = $1
`

func (q *Queries) UpdateAllNotificationByUserId(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, updateAllNotificationByUserId, userID)
	return err
}

const updateNotificationById = `-- name: UpdateNotificationById :exec
UPDATE notifications SET is_read = true WHERE user_id = $1 AND id = $2
`

type UpdateNotificationByIdParams struct {
	UserID int64
	ID     int64
}

func (q *Queries) UpdateNotificationById(ctx context.Context, arg UpdateNotificationByIdParams) error {
	_, err := q.db.Exec(ctx, updateNotificationById, arg.UserID, arg.ID)
	return err
}
