// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification.sql

package db

import (
	"context"
)

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications(user_id, title, message, is_read) VALUES ($1, $2, $3, $4)
`

type CreateNotificationParams struct {
	UserID  int64
	Title   string
	Message string
	IsRead  bool
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.Exec(ctx, createNotification,
		arg.UserID,
		arg.Title,
		arg.Message,
		arg.IsRead,
	)
	return err
}

const getAllNotifications = `-- name: GetAllNotifications :one
SELECT id, user_id, title, message, is_read, created_at FROM  notifications LIMIT 50
`

func (q *Queries) GetAllNotifications(ctx context.Context) (Notification, error) {
	row := q.db.QueryRow(ctx, getAllNotifications)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Message,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationById = `-- name: GetNotificationById :one
SELECT id, user_id, title, message, is_read, created_at from notifications WHERE id = $1
`

func (q *Queries) GetNotificationById(ctx context.Context, id int64) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationById, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Message,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const updateNotificationById = `-- name: UpdateNotificationById :exec
UPDATE notifications
SET
    user_id       = COALESCE($1, user_id),
    title = COALESCE($2, title),
    message = COALESCE($3, message),
    is_read = COALESCE($4, is_read)
WHERE id = $5
`

type UpdateNotificationByIdParams struct {
	UserID  int64
	Title   string
	Message string
	IsRead  bool
	ID      int64
}

func (q *Queries) UpdateNotificationById(ctx context.Context, arg UpdateNotificationByIdParams) error {
	_, err := q.db.Exec(ctx, updateNotificationById,
		arg.UserID,
		arg.Title,
		arg.Message,
		arg.IsRead,
		arg.ID,
	)
	return err
}
