// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: paring_token.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createParingToken = `-- name: CreateParingToken :exec
INSERT INTO pairing_tokens(token, user_id, user_email, expires_at) VALUES ($1, $2, $3, $4)
`

type CreateParingTokenParams struct {
	Token     string
	UserID    int32
	UserEmail string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateParingToken(ctx context.Context, arg CreateParingTokenParams) error {
	_, err := q.db.Exec(ctx, createParingToken,
		arg.Token,
		arg.UserID,
		arg.UserEmail,
		arg.ExpiresAt,
	)
	return err
}

const deleteUsedToken = `-- name: DeleteUsedToken :exec
DELETE  from pairing_tokens WHERE user_email = $1
`

func (q *Queries) DeleteUsedToken(ctx context.Context, userEmail string) error {
	_, err := q.db.Exec(ctx, deleteUsedToken, userEmail)
	return err
}

const getAllParingTokenByEmail = `-- name: GetAllParingTokenByEmail :one
SELECT id, token, user_id, user_email, expires_at from pairing_tokens WHERE user_email = $1
`

func (q *Queries) GetAllParingTokenByEmail(ctx context.Context, userEmail string) (PairingToken, error) {
	row := q.db.QueryRow(ctx, getAllParingTokenByEmail, userEmail)
	var i PairingToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.UserEmail,
		&i.ExpiresAt,
	)
	return i, err
}

const getAllTokenRelatedToUserByEmail = `-- name: GetAllTokenRelatedToUserByEmail :one
SELECT id, token, user_id, user_email, expires_at from pairing_tokens WHERE user_email = $1
`

func (q *Queries) GetAllTokenRelatedToUserByEmail(ctx context.Context, userEmail string) (PairingToken, error) {
	row := q.db.QueryRow(ctx, getAllTokenRelatedToUserByEmail, userEmail)
	var i PairingToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.UserEmail,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserTokenById = `-- name: GetUserTokenById :one
SELECT id, token, user_id, user_email, expires_at from pairing_tokens WHERE id = $1
`

func (q *Queries) GetUserTokenById(ctx context.Context, id int64) (PairingToken, error) {
	row := q.db.QueryRow(ctx, getUserTokenById, id)
	var i PairingToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.UserEmail,
		&i.ExpiresAt,
	)
	return i, err
}
