// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUseSession = `-- name: CreateUseSession :exec
INSERT INTO user_sessions(user_id, token, expires_at) VALUES ($1, $2, $3)
`

type CreateUseSessionParams struct {
	UserID    int64
	Token     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateUseSession(ctx context.Context, arg CreateUseSessionParams) error {
	_, err := q.db.Exec(ctx, createUseSession, arg.UserID, arg.Token, arg.ExpiresAt)
	return err
}

const getAllUserSession = `-- name: GetAllUserSession :one
SELECT id, user_id, token, expires_at, created_at FROM user_sessions LIMIT  50
`

func (q *Queries) GetAllUserSession(ctx context.Context) (UserSession, error) {
	row := q.db.QueryRow(ctx, getAllUserSession)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserSessionById = `-- name: GetUserSessionById :one
SELECT id, user_id, token, expires_at, created_at from user_sessions WHERE id = $1
`

func (q *Queries) GetUserSessionById(ctx context.Context, id int64) (UserSession, error) {
	row := q.db.QueryRow(ctx, getUserSessionById, id)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserSessionById = `-- name: UpdateUserSessionById :exec
UPDATE user_sessions
SET
    user_id = COALESCE($1, user_id),
    token = COALESCE($2, token),
    expires_at = COALESCE($3, expires_at)
WHERE id = $4
`

type UpdateUserSessionByIdParams struct {
	UserID    int64
	Token     string
	ExpiresAt pgtype.Timestamptz
	ID        int64
}

func (q *Queries) UpdateUserSessionById(ctx context.Context, arg UpdateUserSessionByIdParams) error {
	_, err := q.db.Exec(ctx, updateUserSessionById,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}
